---
- name: Deploy todolist on test server
  hosts: test
  become: yes
  tasks:
    - name: Ensure Python 3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Create directory for todolist
      file:
        path: /home/admin/todolist
        state: directory
        owner: admin
        group: admin
        mode: '0755'

    - name: Copy todolist source code from Jenkins workspace
      copy:
        src: /var/lib/jenkins/workspace/todolist-check-code/
        dest: /home/admin/todolist/
        owner: admin
        group: admin
        mode: '0755'

    - name: Install pipenv
      pip:
        name: pipenv
        executable: pip3

    - name: Install project dependencies
      pipenv:
        chdir: /home/admin/todolist/
        state: present
